# Generated by Django 4.2.6 on 2023-10-15 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderimage',
            old_name='order_id',
            new_name='order',
        ),
    ]
